name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI Action"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Kubernetes
      run: |
        minikube start
        minikube update-context

    - name: Deploy to NodePort
      run: |
        minikube kubectl -- create deployment flask-service-node --image=kicbase/echo-server:1.0
        minikube kubectl -- expose deployment flask-service-node --type=NodePort --port=8080

    - name: Check deployment
      run: minikube kubectl -- get services flask-service-node

    - name: Deploy to LoadBalancer
      run: |
        minikube kubectl -- create deployment flask-service-balanced --image=kicbase/echo-server:1.0
        minikube kubectl -- expose deployment flask-service-balanced --type=LoadBalancer --port=8080

