name: Docker Image CD Action

on:
  workflow_run:
    workflows: ["Docker Image CI Action"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Pull Docker image from Dockerhub
      run: sudo docker pull schaavk/flask-template-endterm:latest
      
    - name: Delete old Docker container
      run: sudo docker rm -f flask-template-endterm-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 8080:5000 --name flask-template-endterm-container schaavk/flask-template-endterm
