name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI Action"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Pull Docker image from Dockerhub
      run: sudo docker pull schaavk/flask-template-endterm:latest
      
    - name: Delete old Docker container
      run: sudo docker rm -f flask-template-endterm-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 31230:5000 --name flask-template-endterm-container schaavk/flask-template-endterm

    - name: Set up Kubernetes
      run: |
        minikube start
        minikube update-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
  
    - name: Check deployment
      run: kubectl get all
