name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask-template-endterm:latest
    
    - name: Tag Repository
      run: docker tag flask-template-endterm:latest schaavk/flask-template-endterm:latest

    - name: Push to Dockerhub
      run: docker push schaavk/flask-template-endterm:latest
