name: Docker Image CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Kubernetes
      run: |
        minikube start
        minikube update-context

    - name: Deploy to Kubernetes
      run: |
        minikube kubectl -- apply -f deployment.yaml
        minikube kubectl -- apply -f service.yaml
  
    - name: Check deployment
      run: minikube kubectl -- get all
